import { SongMood, SwimStyle } from './collectible.model';
import {
  BugLocation,
  Creature,
  FishLocation,
  SilhouetteSize,
  CreatureType,
  Song,
  Collectible,
} from './collectible.model';

export const BUG_DATA: { [key: number]: Creature } = {
  0: {
    index: 0,
    name: 'Common Butterfly',
    price: 160,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  1: {
    index: 1,
    name: 'Yellow Butterfly',
    price: 160,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 9 },
    ],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  2: {
    index: 2,
    name: 'Tiger Butterfly',
    price: 240,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 8 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  3: {
    index: 3,
    name: 'Peacock Butterfly',
    price: 2500,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 9 },
    ],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near hybrid flowers',
    haveModelSupplies: false,
  },
  4: {
    index: 4,
    name: 'Common Bluebottle',
    price: 300,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 7 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  5: {
    index: 5,
    name: 'Paper Kite Butterfly',
    price: 1000,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  6: {
    index: 6,
    name: 'Great Purple Emperor',
    price: 3000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 7 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  7: {
    index: 7,
    name: 'Monarch Butterfly',
    price: 140,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 4, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  8: {
    index: 8,
    name: 'Emperor Butterfly',
    price: 4000,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 5, end: 8 },
      { start: 11, end: 2 },
    ],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  9: {
    index: 9,
    name: 'Agrias Butterfly',
    price: 3000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  10: {
    index: 10,
    name: `Rajah Brooke's Birdwing`,
    price: 2500,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 3, end: 8 },
      { start: 11, end: 1 },
    ],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near purple flowers',
    haveModelSupplies: false,
  },
  11: {
    index: 11,
    name: `Queen Alexandra's Birdwing`,
    price: 4000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 16 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  12: {
    index: 12,
    name: 'Moth',
    price: 130,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near light sources',
    haveModelSupplies: false,
  },
  13: {
    index: 13,
    name: 'Atlas Moth',
    price: 3000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  14: {
    index: 14,
    name: 'Madagascan Sunset Moth',
    price: 2500,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 8, end: 16 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  15: {
    index: 15,
    name: 'Long Locust',
    price: 200,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  16: {
    index: 16,
    name: 'Migratory Locust',
    price: 600,
    type: CreatureType.BUG,
    monthsActive: [{ start: 7, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  17: {
    index: 17,
    name: 'Rice Grasshopper',
    price: 160,
    type: CreatureType.BUG,
    monthsActive: [{ start: 10, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  18: {
    index: 18,
    name: 'Grasshopper',
    price: 160,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  19: {
    index: 19,
    name: 'Cricket',
    price: 130,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  20: {
    index: 20,
    name: 'Bell Cricket',
    price: 430,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 9 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  21: {
    index: 21,
    name: 'Mantis',
    price: 430,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  22: {
    index: 22,
    name: 'Orchid Mantis',
    price: 2400,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    notes: 'Appears on white flowers',
    haveModelSupplies: false,
  },
  23: {
    index: 23,
    name: 'Honeybee',
    price: 200,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 6 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  24: {
    index: 24,
    name: 'Wasp',
    price: 2500,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
    notes: 'Will attack; have net in hand',
    haveModelSupplies: false,
  },
  25: {
    index: 25,
    name: 'Brown Cicada',
    price: 250,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  26: {
    index: 26,
    name: 'Robust Cicada',
    price: 300,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  27: {
    index: 27,
    name: 'Giant Cicada',
    price: 600,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  28: {
    index: 28,
    name: 'Walker Cicada',
    price: 400,
    type: CreatureType.BUG,
    monthsActive: [{ start: 7, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  29: {
    index: 29,
    name: 'Evening Cicada',
    price: 660,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [
      { start: 4, end: 8 },
      { start: 16, end: 19 },
    ],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  30: {
    index: 30,
    name: 'Cicada Shell',
    price: 10,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  31: {
    index: 31,
    name: 'Red Dragonfly',
    price: 180,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 9 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  32: {
    index: 32,
    name: 'Darner Dragonfly',
    price: 230,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 9 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  33: {
    index: 33,
    name: 'Banded Dragonfly',
    price: 4500,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  34: {
    index: 34,
    name: 'Damselfly',
    price: 500,
    type: CreatureType.BUG,
    monthsActive: [{ start: 10, end: 1 }],
    timesActive: [],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  35: {
    index: 35,
    name: 'Firefly',
    price: 300,
    type: CreatureType.BUG,
    monthsActive: [{ start: 5, end: 5 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  36: {
    index: 36,
    name: 'Mole Cricket',
    price: 500,
    type: CreatureType.BUG,
    monthsActive: [{ start: 10, end: 4 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.UNDERGROUND],
    collected: false,
    haveModel: false,
    notes: 'Can be heard chirping when near',
    haveModelSupplies: false,
  },
  37: {
    index: 37,
    name: 'Pondskater',
    price: 130,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.WATER_POND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  38: {
    index: 38,
    name: 'Diving Beetle',
    price: 800,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.WATER_POND, BugLocation.WATER_RIVER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  39: {
    index: 39,
    name: 'Giant Water Bug',
    price: 2000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.WATER_POND, BugLocation.WATER_RIVER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  40: {
    index: 40,
    name: 'Stinkbug',
    price: 120,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  41: {
    index: 41,
    name: 'Man-faced Stink Bug',
    price: 1000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  42: {
    index: 42,
    name: 'Ladybug',
    price: 200,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 9, end: 9 },
    ],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  43: {
    index: 43,
    name: 'Tiger Beetle',
    price: 1500,
    type: CreatureType.BUG,
    monthsActive: [{ start: 1, end: 10 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  44: {
    index: 44,
    name: 'Jewel Beetle',
    price: 2400,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  45: {
    index: 45,
    name: 'Violin Beetle',
    price: 450,
    type: CreatureType.BUG,
    monthsActive: [
      { start: 4, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  46: {
    index: 46,
    name: 'Citrus Long-horned Beetle',
    price: 350,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  47: {
    index: 47,
    name: 'Rosalia Batesi Beetle',
    price: 3000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  48: {
    index: 48,
    name: 'Blue Weevil Beetle',
    price: 800,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  49: {
    index: 49,
    name: 'Dung Beetle',
    price: 3000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 11, end: 1 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Appears pushing snowballs',
    haveModelSupplies: false,
  },
  50: {
    index: 50,
    name: 'Earth-boring Dung Beetle',
    price: 300,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  51: {
    index: 51,
    name: 'Scarab Beetle',
    price: 10000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 23, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  52: {
    index: 52,
    name: 'Drone Beetle',
    price: 200,
    type: CreatureType.BUG,
    monthsActive: [{ start: 5, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  53: {
    index: 53,
    name: 'Goliath Beetle',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  54: {
    index: 54,
    name: 'Saw Stag',
    price: 2000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  55: {
    index: 55,
    name: 'Miyama Stag',
    price: 1000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  56: {
    index: 56,
    name: 'Giant Stag',
    price: 10000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 23, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  57: {
    index: 57,
    name: 'Rainbow Stag',
    price: 6000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  58: {
    index: 58,
    name: 'Cyclommatus Stag',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  59: {
    index: 59,
    name: 'Golden Stag',
    price: 12000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  60: {
    index: 60,
    name: 'Giraffe Stag',
    price: 12000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  61: {
    index: 61,
    name: 'Horned Dynastid',
    price: 1350,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  62: {
    index: 62,
    name: 'Horned Atlas',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  63: {
    index: 63,
    name: 'Horned Elephant',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  64: {
    index: 64,
    name: 'Horned Hercules',
    price: 12000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  65: {
    index: 65,
    name: 'Walking Stick',
    price: 600,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 10 }],
    timesActive: [
      { start: 4, end: 8 },
      { start: 17, end: 19 },
    ],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  66: {
    index: 66,
    name: 'Walking Leaf',
    price: 600,
    type: CreatureType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Appears disguised as furniture leaf',
    haveModelSupplies: false,
  },
  67: {
    index: 67,
    name: 'Bagworm',
    price: 600,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  68: {
    index: 68,
    name: 'Ant',
    price: 80,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.ROTTEN_FOOD],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  69: {
    index: 69,
    name: 'Hermit Crab',
    price: 1000,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.BEACH],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  70: {
    index: 70,
    name: 'Wharf Roach',
    price: 200,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.BEACH],
    collected: false,
    haveModel: false,
    notes: 'Appears on rocks',
    haveModelSupplies: false,
  },
  71: {
    index: 71,
    name: 'Fly',
    price: 60,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TRASH],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  72: {
    index: 72,
    name: 'Mosquito',
    price: 130,
    type: CreatureType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 17, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  73: {
    index: 73,
    name: 'Flea',
    price: 70,
    type: CreatureType.BUG,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [],
    location: [BugLocation.VILLAGER],
    collected: false,
    haveModel: false,
    notes: 'Appears jumping on villagers',
    haveModelSupplies: false,
  },
  74: {
    index: 74,
    name: 'Snail',
    price: 250,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.ROCK, BugLocation.SHRUB],
    collected: false,
    haveModel: false,
    notes: 'Appears during rainy weather',
    haveModelSupplies: false,
  },
  75: {
    index: 75,
    name: 'Pill Bug',
    price: 250,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 23, end: 16 }],
    location: [BugLocation.ROCK],
    collected: false,
    haveModel: false,
    notes: 'Appears upon striking rocks with tools',
    haveModelSupplies: false,
  },
  76: {
    index: 76,
    name: 'Centipede',
    price: 300,
    type: CreatureType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 16, end: 23 }],
    location: [BugLocation.ROCK],
    collected: false,
    haveModel: false,
    notes: 'Appears upon striking rocks with tools',
    haveModelSupplies: false,
  },
  77: {
    index: 77,
    name: 'Spider',
    price: 480,
    type: CreatureType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  78: {
    index: 78,
    name: 'Tarantula',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 10, end: 3 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Will attack if threatened by net, approach when calm',
    haveModelSupplies: false,
  },
  79: {
    index: 79,
    name: 'Scorpion',
    price: 8000,
    type: CreatureType.BUG,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Will attack if threatened by net, approach when calm',
    haveModelSupplies: false,
  },
};

export const FISH_DATA: { [key: number]: Creature } = {
  0: {
    index: 0,
    name: 'Bitterling',
    price: 900,
    type: CreatureType.FISH,
    monthsActive: [{ start: 10, end: 2 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  1: {
    index: 1,
    name: 'Pale Chub',
    price: 160,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  2: {
    index: 2,
    name: 'Crucian Carp',
    price: 160,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  3: {
    index: 3,
    name: 'Dace',
    price: 240,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  4: {
    index: 4,
    name: 'Carp',
    price: 300,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  5: {
    index: 5,
    name: 'Koi',
    price: 4000,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  6: {
    index: 6,
    name: 'Goldfish',
    price: 1300,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  7: {
    index: 7,
    name: 'Pop-eyed Goldfish',
    price: 1300,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  8: {
    index: 8,
    name: 'Ranchu Goldfish',
    price: 4500,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  9: {
    index: 9,
    name: 'Killifish',
    price: 300,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 7 }],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  10: {
    index: 10,
    name: 'Crawfish',
    price: 200,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  11: {
    index: 11,
    name: 'Soft-shelled Turtle',
    price: 3750,
    type: CreatureType.FISH,
    monthsActive: [{ start: 7, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  12: {
    index: 12,
    name: 'Snapping Turtle',
    price: 5000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 9 }],
    timesActive: [{ start: 21, end: 4 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  13: {
    index: 13,
    name: 'Tadpole',
    price: 100,
    type: CreatureType.FISH,
    monthsActive: [{ start: 2, end: 6 }],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  14: {
    index: 14,
    name: 'Frog',
    price: 120,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 7 }],
    timesActive: [],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  15: {
    index: 15,
    name: 'Freshwater Goby',
    price: 400,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  16: {
    index: 16,
    name: 'Loach',
    price: 400,
    type: CreatureType.FISH,
    monthsActive: [{ start: 2, end: 4 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  17: {
    index: 17,
    name: 'Catfish',
    price: 800,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  18: {
    index: 18,
    name: 'Giant Snakehead',
    price: 4500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 7 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  19: {
    index: 19,
    name: 'Bluegill',
    price: 180,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  20: {
    index: 20,
    name: 'Yellow Perch',
    price: 300,
    type: CreatureType.FISH,
    monthsActive: [{ start: 9, end: 2 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  21: {
    index: 21,
    name: 'Black Bass',
    price: 400,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  22: {
    index: 22,
    name: 'Tilapia',
    price: 800,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 9 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  23: {
    index: 23,
    name: 'Pike',
    price: 1800,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 11 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  24: {
    index: 24,
    name: 'Pond Smelt',
    price: 500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 11, end: 1 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  25: {
    index: 25,
    name: 'Sweetfish',
    price: 900,
    type: CreatureType.FISH,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  26: {
    index: 26,
    name: 'Cherry Salmon',
    price: 1000,
    type: CreatureType.FISH,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER_CLIFF],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  27: {
    index: 27,
    name: 'Char',
    price: 3800,
    type: CreatureType.FISH,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER_CLIFF],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  28: {
    index: 28,
    name: 'Golden Trout',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [
      { start: 2, end: 4 },
      { start: 8, end: 10 },
    ],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER_CLIFF],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  29: {
    index: 29,
    name: 'Stringfish',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 11, end: 2 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER_CLIFF],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  30: {
    index: 30,
    name: 'Salmon',
    price: 700,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 8 }],
    timesActive: [],
    location: [FishLocation.RIVER_MOUTH],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  31: {
    index: 31,
    name: 'King Salmon',
    price: 1800,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 8 }],
    timesActive: [],
    location: [FishLocation.RIVER_MOUTH],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  32: {
    index: 32,
    name: 'Mitten Crab',
    price: 2000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  33: {
    index: 33,
    name: 'Guppy',
    price: 1300,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  34: {
    index: 34,
    name: 'Nibble Fish',
    price: 1500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  35: {
    index: 35,
    name: 'Angelfish',
    price: 3000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  36: {
    index: 36,
    name: 'Betta',
    price: 2500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  37: {
    index: 37,
    name: 'Neon Tetra',
    price: 500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  38: {
    index: 38,
    name: 'Rainbowfish',
    price: 800,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 9, end: 16 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  39: {
    index: 39,
    name: 'Piranha',
    price: 2500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [
      { start: 9, end: 16 },
      { start: 21, end: 4 },
    ],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  40: {
    index: 40,
    name: 'Arowana',
    price: 10000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  41: {
    index: 41,
    name: 'Dorado',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 4, end: 21 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  42: {
    index: 42,
    name: 'Gar',
    price: 6000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.POND],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  43: {
    index: 43,
    name: 'Arapaima',
    price: 10000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  44: {
    index: 44,
    name: 'Saddled Bichir',
    price: 4000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 21, end: 4 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  45: {
    index: 45,
    name: 'Sturgeon',
    price: 10000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 2 }],
    timesActive: [{ start: 21, end: 4 }],
    location: [FishLocation.RIVER],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  46: {
    index: 46,
    name: 'Sea Butterfly',
    price: 1000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 11, end: 2 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  47: {
    index: 47,
    name: 'Sea Horse',
    price: 1100,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 10 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  48: {
    index: 48,
    name: 'Clown Fish',
    price: 650,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALLEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  49: {
    index: 49,
    name: 'Surgeonfish',
    price: 1000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  50: {
    index: 50,
    name: 'Butterfly Fish',
    price: 1000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  51: {
    index: 51,
    name: 'Napoleonfish',
    price: 10000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 4, end: 21 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  52: {
    index: 52,
    name: 'Zebra Turkeyfish',
    price: 500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  53: {
    index: 53,
    name: 'Blowfish',
    price: 5000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 10, end: 1 }],
    timesActive: [{ start: 21, end: 4 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  54: {
    index: 54,
    name: 'Puffer Fish',
    price: 250,
    type: CreatureType.FISH,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  55: {
    index: 55,
    name: 'Anchovy',
    price: 200,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 4, end: 21 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  56: {
    index: 56,
    name: 'Horse Mackerel',
    price: 150,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  57: {
    index: 57,
    name: 'Barred Knifejaw',
    price: 5000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  58: {
    index: 58,
    name: 'Sea Bass',
    price: 400,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  59: {
    index: 59,
    name: 'Red Snapper',
    price: 3000,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  60: {
    index: 60,
    name: 'Dab',
    price: 300,
    type: CreatureType.FISH,
    monthsActive: [{ start: 9, end: 3 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  61: {
    index: 61,
    name: 'Olive Flounder',
    price: 800,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  62: {
    index: 62,
    name: 'Squid',
    price: 500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 11, end: 7 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.MEDIUM,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  63: {
    index: 63,
    name: 'Moray Eel',
    price: 2000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 7, end: 9 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.NARROW,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  64: {
    index: 64,
    name: 'Ribbon Eel',
    price: 600,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 9 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.NARROW,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  65: {
    index: 65,
    name: 'Tuna',
    price: 7000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 10, end: 3 }],
    timesActive: [],
    location: [FishLocation.PIER],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  66: {
    index: 66,
    name: 'Blue Marlin',
    price: 10000,
    type: CreatureType.FISH,
    monthsActive: [
      { start: 6, end: 8 },
      { start: 10, end: 3 },
    ],
    timesActive: [],
    location: [FishLocation.PIER],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  67: {
    index: 67,
    name: 'Giant Trevally',
    price: 4500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [],
    location: [FishLocation.PIER],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  68: {
    index: 68,
    name: 'Mahi-mahi',
    price: 6000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [],
    location: [FishLocation.PIER],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  69: {
    index: 69,
    name: 'Ocean Sunfish',
    price: 4000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [{ start: 4, end: 21 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  70: {
    index: 70,
    name: 'Ray',
    price: 3000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 4, end: 21 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.EXTRA_LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  71: {
    index: 71,
    name: 'Saw Shark',
    price: 12000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  72: {
    index: 72,
    name: 'Hammerhead Shark',
    price: 8000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  73: {
    index: 73,
    name: 'Great White Shark',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  74: {
    index: 74,
    name: 'Whale Shark',
    price: 13000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  75: {
    index: 75,
    name: 'Suckerfish',
    price: 1500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGE_FIN,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  76: {
    index: 76,
    name: 'Football Fish',
    price: 2500,
    type: CreatureType.FISH,
    monthsActive: [{ start: 10, end: 2 }],
    timesActive: [{ start: 16, end: 9 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGE,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  77: {
    index: 77,
    name: 'Oarfish',
    price: 9000,
    type: CreatureType.FISH,
    monthsActive: [{ start: 11, end: 4 }],
    timesActive: [],
    location: [FishLocation.SEA],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  78: {
    index: 78,
    name: 'Barreleye',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [{ start: 21, end: 4 }],
    location: [FishLocation.SEA],
    size: SilhouetteSize.SMALL,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
  79: {
    index: 79,
    name: 'Coelacanth',
    price: 15000,
    type: CreatureType.FISH,
    monthsActive: [],
    timesActive: [],
    location: [FishLocation.SEA_RAINY],
    size: SilhouetteSize.LARGEST,
    collected: false,
    haveModel: false,
    haveModelSupplies: false,
  },
};

export const SEA_CREATURE_DATA: { [key: number]: Creature } = {
  0: {
    index: 0,
    name: 'Seaweed',
    price: 600,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 9, end: 6 }],
    timesActive: [],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.STATIONARY,
    collected: false,
  },
  1: {
    index: 1,
    name: 'Sea grapes',
    price: 900,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.STATIONARY,
    collected: false,
  },
  2: {
    index: 2,
    name: 'Sea cucumber',
    price: 500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 10, end: 3 }],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  3: {
    index: 3,
    name: 'Sea pig',
    price: 10000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 10, end: 1 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.FAST_LONG,
    collected: false,
  },
  4: {
    index: 4,
    name: 'Sea star',
    price: 500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_SHORT,
    collected: false,
  },
  5: {
    index: 5,
    name: 'Sea urchin',
    price: 1700,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  6: {
    index: 6,
    name: 'Slate pencil urchin',
    price: 2000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_CONSISTENT,
    collected: false,
  },
  7: {
    index: 7,
    name: 'Sea anemone',
    price: 500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.STATIONARY,
    collected: false,
  },
  8: {
    index: 8,
    name: 'Moon jellyfish',
    price: 600,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  9: {
    index: 9,
    name: 'Sea slug',
    price: 600,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALLEST,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  10: {
    index: 10,
    name: 'Pearl oyster',
    price: 2800,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_LONG,
    collected: false,
  },
  11: {
    index: 11,
    name: 'Mussel',
    price: 1500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 5, end: 11 }],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  12: {
    index: 12,
    name: 'Oyster',
    price: 1100,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 8, end: 1 }],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.MODERATE_SHORT,
    collected: false,
  },
  13: {
    index: 13,
    name: 'Scallop',
    price: 1200,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.SLOW_LONG,
    collected: false,
  },
  14: {
    index: 14,
    name: 'Whelk',
    price: 1000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  15: {
    index: 15,
    name: 'Turban shell',
    price: 1000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [
      { start: 2, end: 4 },
      { start: 8, end: 11 },
    ],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  16: {
    index: 16,
    name: 'Abalone',
    price: 2000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 5, end: 0 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_CONSISTENT,
    collected: false,
  },
  17: {
    index: 17,
    name: 'Gigas giant clam',
    price: 15000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [],
    size: SilhouetteSize.LARGEST,
    swimStyle: SwimStyle.FAST_LONG,
    collected: false,
  },
  18: {
    index: 18,
    name: 'Chambered nautilus',
    price: 1800,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  19: {
    index: 19,
    name: 'Octopus',
    price: 1200,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_LONG,
    collected: false,
  },
  20: {
    index: 20,
    name: 'Umbrella octopus',
    price: 6000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.FAST_LONG,
    collected: false,
  },
  21: {
    index: 21,
    name: 'Vampire squid',
    price: 10000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 4, end: 7 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_LONG,
    collected: false,
  },
  22: {
    index: 22,
    name: 'Firefly squid',
    price: 1400,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 2, end: 5 }],
    timesActive: [{ start: 21, end: 4 }],
    size: SilhouetteSize.SMALLEST,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  23: {
    index: 23,
    name: 'Gazami crab',
    price: 2200,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 5, end: 10 }],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_LONG,
    collected: false,
  },
  24: {
    index: 24,
    name: 'Dungeoness crab',
    price: 1900,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 10, end: 4 }],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.MODERATE_CONSISTENT,
    collected: false,
  },
  25: {
    index: 25,
    name: 'Snow crab',
    price: 6000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 10, end: 3 }],
    timesActive: [],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.FAST_SHORT,
    collected: false,
  },
  26: {
    index: 26,
    name: 'Red king crab',
    price: 8000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 10, end: 2 }],
    timesActive: [],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.FAST_CONSISTENT,
    collected: false,
  },
  27: {
    index: 27,
    name: 'Acorn barnacle',
    price: 600,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALLEST,
    swimStyle: SwimStyle.STATIONARY,
    collected: false,
  },
  28: {
    index: 28,
    name: 'Spider crab',
    price: 12000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 2, end: 3 }],
    timesActive: [],
    size: SilhouetteSize.LARGEST,
    swimStyle: SwimStyle.FAST_CONSISTENT,
    collected: false,
  },
  29: {
    index: 29,
    name: 'Tiger prawn',
    price: 3000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.MODERATE_CONSISTENT,
    collected: false,
  },
  30: {
    index: 30,
    name: 'Sweet shrimp',
    price: 1400,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 8, end: 1 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  31: {
    index: 31,
    name: 'Mantis shrimp',
    price: 2500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.FAST_SHORT,
    collected: false,
  },
  32: {
    index: 32,
    name: 'Spiny lobster',
    price: 5000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 9, end: 11 }],
    timesActive: [{ start: 21, end: 4 }],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.FAST_CONSISTENT,
    collected: false,
  },
  33: {
    index: 33,
    name: 'Lobster',
    price: 4500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [
      { start: 3, end: 5 },
      { start: 11, end: 0 },
    ],
    timesActive: [],
    size: SilhouetteSize.LARGE,
    swimStyle: SwimStyle.FAST_CONSISTENT,
    collected: false,
  },
  34: {
    index: 34,
    name: 'Giant isopod',
    price: 12000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 6, end: 9 }],
    timesActive: [
      { start: 9, end: 16 },
      { start: 21, end: 4 },
    ],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.FAST_LONG,
    collected: false,
  },
  35: {
    index: 35,
    name: 'Horseshoe crab',
    price: 2500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [{ start: 21, end: 4 }],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.FAST_SHORT,
    collected: false,
  },
  36: {
    index: 36,
    name: 'Sea pineapple',
    price: 1500,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [],
    timesActive: [],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_LONG,
    collected: false,
  },
  37: {
    index: 37,
    name: 'Spotted garden eel',
    price: 1100,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 4, end: 21 }],
    size: SilhouetteSize.SMALL,
    swimStyle: SwimStyle.SLOW_CONSISTENT,
    collected: false,
  },
  38: {
    index: 38,
    name: 'Flatworm',
    price: 700,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 7, end: 8 }],
    timesActive: [{ start: 16, end: 9 }],
    size: SilhouetteSize.SMALLEST,
    swimStyle: SwimStyle.SLOW_SHORT,
    collected: false,
  },
  39: {
    index: 39,
    name: `Venus' flower basket`,
    price: 5000,
    type: CreatureType.SEA_CREATURE,
    monthsActive: [{ start: 9, end: 1 }],
    timesActive: [],
    size: SilhouetteSize.MEDIUM,
    swimStyle: SwimStyle.FAST_LONG,
    collected: false,
  },
};

export const SONG_DATA: { [key: number]: Song } = {
  0: {
    index: 0,
    name: 'Agent K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  1: {
    index: 1,
    name: 'Aloha K.K.',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  2: {
    index: 2,
    name: 'Animal City',
    price: 800,
    collected: false,
    mood: SongMood.REQUEST,
  },
  3: {
    index: 3,
    name: 'Bubblegum K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  4: {
    index: 4,
    name: 'Café K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  5: {
    index: 5,
    name: 'Comrade K.K.',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  6: {
    index: 6,
    name: 'DJ K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  7: {
    index: 7,
    name: `Drivin'`,
    price: 800,
    collected: false,
    mood: SongMood.REQUEST,
  },
  8: {
    index: 8,
    name: 'Farewell',
    price: 800,
    collected: false,
    mood: SongMood.REQUEST,
  },
  9: {
    index: 9,
    name: 'Forest Life',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  10: {
    index: 10,
    name: 'Go K.K. Rider',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  11: {
    index: 11,
    name: 'Hypno K.K.',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  12: {
    index: 12,
    name: 'I Love You',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  13: {
    index: 13,
    name: 'Imperial K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  14: {
    index: 14,
    name: 'K.K. Adventure',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  15: {
    index: 15,
    name: 'K.K. Aria',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  16: {
    index: 16,
    name: 'K.K. Ballad',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  17: {
    index: 17,
    name: 'K.K. Bazaar',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  18: {
    index: 18,
    name: 'K.K. Birthday',
    price: 800,
    collected: false,
    mood: SongMood.REQUEST,
  },
  19: {
    index: 19,
    name: 'K.K. Blues',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  20: {
    index: 20,
    name: 'K.K. Bossa',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  21: {
    index: 21,
    name: 'K.K. Calypso',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  22: {
    index: 22,
    name: 'K.K. Casbah',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  23: {
    index: 23,
    name: 'K.K. Chorale',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  24: {
    index: 24,
    name: 'K.K. Condor',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  25: {
    index: 25,
    name: 'K.K. Country',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  26: {
    index: 26,
    name: `K.K. Cruisin'`,
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  27: {
    index: 27,
    name: 'K.K. D&B',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  28: {
    index: 28,
    name: 'K.K. Dirge',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  29: {
    index: 29,
    name: 'K.K. Disco',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  30: {
    index: 30,
    name: 'K.K. Dixie',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  31: {
    index: 31,
    name: 'K.K. Étude',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  32: {
    index: 32,
    name: 'K.K. Faire',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  33: {
    index: 33,
    name: 'K.K. Flamenco',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  34: {
    index: 34,
    name: 'K.K. Folk',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  35: {
    index: 35,
    name: 'K.K. Fusion',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  36: {
    index: 36,
    name: 'K.K. Groove',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  37: {
    index: 37,
    name: 'K.K. Gumbo',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  38: {
    index: 38,
    name: 'K.K. House',
    price: 800,
    collected: false,
    mood: SongMood.CHEERFUL_UPBEAT,
  },
  39: {
    index: 39,
    name: 'K.K. Island',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  40: {
    index: 40,
    name: 'K.K. Jazz',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  41: {
    index: 41,
    name: 'K.K. Jongara',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  42: {
    index: 42,
    name: 'K.K. Lament',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  43: {
    index: 43,
    name: 'K.K. Love Song',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  44: {
    index: 44,
    name: 'K.K. Lullaby',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  45: {
    index: 45,
    name: 'K.K. Mambo',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  46: {
    index: 46,
    name: 'K.K. Marathon',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  47: {
    index: 47,
    name: 'K.K. March',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  48: {
    index: 48,
    name: 'K.K. Mariachi',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  49: {
    index: 49,
    name: 'K.K. Metal',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  50: {
    index: 50,
    name: 'K.K. Milonga',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  51: {
    index: 51,
    name: 'K.K. Moody',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  52: {
    index: 52,
    name: 'K.K. Oasis',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  53: {
    index: 53,
    name: 'K.K. Parade',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  54: {
    index: 54,
    name: 'K.K. Ragtime',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  55: {
    index: 55,
    name: 'K.K. Rally',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  56: {
    index: 56,
    name: 'K.K. Reggae',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  57: {
    index: 57,
    name: 'K.K. Rock',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  58: {
    index: 58,
    name: 'K.K. Rockabilly',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  59: {
    index: 59,
    name: 'K.K. Safari',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  60: {
    index: 60,
    name: 'K.K. Salsa',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  61: {
    index: 61,
    name: 'K.K. Samba',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  62: {
    index: 62,
    name: 'K.K. Ska',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  63: {
    index: 63,
    name: 'K.K. Sonata',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  64: {
    index: 64,
    name: 'K.K. Song',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  65: {
    index: 65,
    name: 'K.K. Soul',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  66: {
    index: 66,
    name: 'K.K. Steppe',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  67: {
    index: 67,
    name: 'K.K. Stroll',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  68: {
    index: 68,
    name: 'K.K. Swing',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  69: {
    index: 69,
    name: 'K.K. Synth',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  70: {
    index: 70,
    name: 'K.K. Tango',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  71: {
    index: 71,
    name: 'K.K. Technopop',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  72: {
    index: 72,
    name: 'K.K. Waltz',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  73: {
    index: 73,
    name: 'K.K. Western',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  74: {
    index: 74,
    name: 'King K.K.',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  75: {
    index: 75,
    name: 'Lucky K.K.',
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  76: {
    index: 76,
    name: 'Marine Song 2001',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  77: {
    index: 77,
    name: 'Mountain Song',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  78: {
    index: 78,
    name: 'Mr. K.K.',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  79: {
    index: 79,
    name: 'My Place',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  80: {
    index: 80,
    name: 'Neapolitan',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  81: {
    index: 81,
    name: 'Only Me',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  82: {
    index: 82,
    name: 'Pondering',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  83: {
    index: 83,
    name: `Rockin' K.K.`,
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  84: {
    index: 84,
    name: 'Soulful K.K.',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  85: {
    index: 85,
    name: 'Space K.K.',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  86: {
    index: 86,
    name: 'Spring Blossoms',
    price: 800,
    collected: false,
    mood: SongMood.GOOD,
  },
  87: {
    index: 87,
    name: 'Stale Cupcakes',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  88: {
    index: 88,
    name: 'Steep Hill',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  89: {
    index: 89,
    name: `Surfin' K.K.`,
    price: 800,
    collected: false,
    mood: SongMood.GRUMPY,
  },
  90: {
    index: 90,
    name: 'The K. Funk',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  91: {
    index: 91,
    name: 'To the Edge',
    price: 800,
    collected: false,
    mood: SongMood.HARD_TO_SAY,
  },
  92: {
    index: 92,
    name: 'Two Days Ago',
    price: 800,
    collected: false,
    mood: SongMood.BLUE,
  },
  93: {
    index: 93,
    name: 'Wandering',
    price: 800,
    collected: false,
    mood: SongMood.LAID_BACK,
  },
  94: {
    index: 94,
    name: 'Welcome Horizons',
    price: 800,
    collected: false,
    mood: SongMood.REQUEST,
  },
};
