import { CritterType } from '../../critter-tracker/models/critter-tracker.model';
import { BugLocation, Critter } from './critter.model';

export const BUG_DATA: { [key: number]: Critter } = {
  0: {
    index: 0,
    name: 'Common Butterfly',
    price: 160,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  1: {
    index: 1,
    name: 'Yellow Butterfly',
    price: 160,
    type: CritterType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 9 },
    ],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  2: {
    index: 2,
    name: 'Tiger Butterfly',
    price: 240,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 8 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  3: {
    index: 3,
    name: 'Peacock Butterfly',
    price: 2500,
    type: CritterType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 8, end: 9 },
    ],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near hybrid flowers',
  },
  4: {
    index: 4,
    name: 'Common Bluebottle',
    price: 300,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 7 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  5: {
    index: 5,
    name: 'Paper Kite Butterfly',
    price: 1000,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  6: {
    index: 6,
    name: 'Great Purple Emperor',
    price: 3000,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 7 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  7: {
    index: 7,
    name: 'Monarch Butterfly',
    price: 140,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 4, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  8: {
    index: 8,
    name: 'Emperor Butterfly',
    price: 4000,
    type: CritterType.BUG,
    monthsActive: [
      { start: 5, end: 8 },
      { start: 11, end: 2 },
    ],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  9: {
    index: 9,
    name: 'Agrias Butterfly',
    price: 3000,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  10: {
    index: 10,
    name: `Rajah Brooke's Birdwing`,
    price: 2500,
    type: CritterType.BUG,
    monthsActive: [
      { start: 3, end: 8 },
      { start: 11, end: 1 },
    ],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near purple flowers',
  },
  11: {
    index: 11,
    name: `Queen Alexandra's Birdwing`,
    price: 4000,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 16 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  12: {
    index: 12,
    name: 'Moth',
    price: 130,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
    notes: 'Appears near light sources',
  },
  13: {
    index: 13,
    name: 'Atlas Moth',
    price: 3000,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  14: {
    index: 14,
    name: 'Madagascan Sunset Moth',
    price: 2500,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 8, end: 16 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  15: {
    index: 15,
    name: 'Long Locust',
    price: 200,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  16: {
    index: 16,
    name: 'Migratory Locust',
    price: 600,
    type: CritterType.BUG,
    monthsActive: [{ start: 7, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  17: {
    index: 17,
    name: 'Rice Grasshopper',
    price: 160,
    type: CritterType.BUG,
    monthsActive: [{ start: 10, end: 10 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  18: {
    index: 18,
    name: 'Grasshopper',
    price: 160,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  19: {
    index: 19,
    name: 'Cricket',
    price: 130,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 10 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  20: {
    index: 20,
    name: 'Bell Cricket',
    price: 430,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 9 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  21: {
    index: 21,
    name: 'Mantis',
    price: 430,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
  },
  22: {
    index: 22,
    name: 'Orchid Mantis',
    price: 2400,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
    notes: 'Appears on white flowers',
  },
  23: {
    index: 23,
    name: 'Honeybee',
    price: 200,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 6 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  24: {
    index: 24,
    name: 'Wasp',
    price: 2500,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
    notes: 'Will attack; have net in hand',
  },
  25: {
    index: 25,
    name: 'Brown Cicada',
    price: 250,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  26: {
    index: 26,
    name: 'Robust Cicada',
    price: 300,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  27: {
    index: 27,
    name: 'Giant Cicada',
    price: 600,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  28: {
    index: 28,
    name: 'Walker Cicada',
    price: 400,
    type: CritterType.BUG,
    monthsActive: [{ start: 7, end: 8 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  29: {
    index: 29,
    name: 'Evening Cicada',
    price: 660,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [
      { start: 4, end: 8 },
      { start: 16, end: 19 },
    ],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  30: {
    index: 30,
    name: 'Cicada Shell',
    price: 10,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  31: {
    index: 31,
    name: 'Red Dragonfly',
    price: 180,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 9 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  32: {
    index: 32,
    name: 'Darner Dragonfly',
    price: 230,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 9 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  33: {
    index: 33,
    name: 'Banded Dragonfly',
    price: 4500,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  34: {
    index: 34,
    name: 'Damselfly',
    price: 500,
    type: CritterType.BUG,
    monthsActive: [{ start: 10, end: 1 }],
    timesActive: [],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  35: {
    index: 35,
    name: 'Firefly',
    price: 300,
    type: CritterType.BUG,
    monthsActive: [{ start: 5, end: 5 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  36: {
    index: 36,
    name: 'Mole Cricket',
    price: 500,
    type: CritterType.BUG,
    monthsActive: [{ start: 10, end: 4 }],
    timesActive: [{ start: 4, end: 19 }],
    location: [BugLocation.UNDERGROUND],
    collected: false,
    haveModel: false,
    notes: 'Can be heard chirping when near',
  },
  37: {
    index: 37,
    name: 'Pondskater',
    price: 130,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.WATER_POND],
    collected: false,
    haveModel: false,
  },
  38: {
    index: 38,
    name: 'Diving Beetle',
    price: 800,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [{ start: 8, end: 19 }],
    location: [BugLocation.WATER_POND, BugLocation.WATER_RIVER],
    collected: false,
    haveModel: false,
  },
  39: {
    index: 39,
    name: 'Giant Water Bug',
    price: 2000,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 8 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.WATER_POND, BugLocation.WATER_RIVER],
    collected: false,
    haveModel: false,
  },
  40: {
    index: 40,
    name: 'Stinkbug',
    price: 120,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
  },
  41: {
    index: 41,
    name: 'Man-faced Stink Bug',
    price: 1000,
    type: CritterType.BUG,
    monthsActive: [{ start: 2, end: 10 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
  },
  42: {
    index: 42,
    name: 'Ladybug',
    price: 200,
    type: CritterType.BUG,
    monthsActive: [
      { start: 2, end: 5 },
      { start: 9, end: 9 },
    ],
    timesActive: [{ start: 8, end: 17 }],
    location: [BugLocation.FLOWER],
    collected: false,
    haveModel: false,
  },
  43: {
    index: 43,
    name: 'Tiger Beetle',
    price: 1500,
    type: CritterType.BUG,
    monthsActive: [{ start: 1, end: 10 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  44: {
    index: 44,
    name: 'Jewel Beetle',
    price: 2400,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
  },
  45: {
    index: 45,
    name: 'Violin Beetle',
    price: 450,
    type: CritterType.BUG,
    monthsActive: [
      { start: 4, end: 5 },
      { start: 8, end: 10 },
    ],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
  },
  46: {
    index: 46,
    name: 'Citrus Long-horned Beetle',
    price: 350,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
  },
  47: {
    index: 47,
    name: 'Rosalia Batesi Beetle',
    price: 3000,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 8 }],
    timesActive: [],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
  },
  48: {
    index: 48,
    name: 'Blue Weevil Beetle',
    price: 800,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  49: {
    index: 49,
    name: 'Dung Beetle',
    price: 3000,
    type: CritterType.BUG,
    monthsActive: [{ start: 11, end: 1 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Appears pushing snowballs',
  },
  50: {
    index: 50,
    name: 'Earth-boring Dung Beetle',
    price: 300,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 8 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
  },
  51: {
    index: 51,
    name: 'Scarab Beetle',
    price: 10000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 23, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  52: {
    index: 52,
    name: 'Drone Beetle',
    price: 200,
    type: CritterType.BUG,
    monthsActive: [{ start: 5, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  53: {
    index: 53,
    name: 'Goliath Beetle',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  54: {
    index: 54,
    name: 'Saw Stag',
    price: 2000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  55: {
    index: 55,
    name: 'Miyama Stag',
    price: 1000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  56: {
    index: 56,
    name: 'Giant Stag',
    price: 10000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 23, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  57: {
    index: 57,
    name: 'Rainbow Stag',
    price: 6000,
    type: CritterType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.TREE_STUMP],
    collected: false,
    haveModel: false,
  },
  58: {
    index: 58,
    name: 'Cyclommatus Stag',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  59: {
    index: 59,
    name: 'Golden Stag',
    price: 12000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  60: {
    index: 60,
    name: 'Giraffe Stag',
    price: 12000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  61: {
    index: 61,
    name: 'Horned Dynastid',
    price: 1350,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  62: {
    index: 62,
    name: 'Horned Atlas',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  63: {
    index: 63,
    name: 'Horned Elephant',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  64: {
    index: 64,
    name: 'Horned Hercules',
    price: 12000,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [{ start: 17, end: 8 }],
    location: [BugLocation.TREE_COCONUT],
    collected: false,
    haveModel: false,
  },
  65: {
    index: 65,
    name: 'Walking Stick',
    price: 600,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 10 }],
    timesActive: [
      { start: 4, end: 8 },
      { start: 17, end: 19 },
    ],
    location: [BugLocation.TREE_TRUNK],
    collected: false,
    haveModel: false,
  },
  66: {
    index: 66,
    name: 'Walking Leaf',
    price: 600,
    type: CritterType.BUG,
    monthsActive: [{ start: 6, end: 7 }],
    timesActive: [],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Appears disguised as furniture leaf',
  },
  67: {
    index: 67,
    name: 'Bagworm',
    price: 600,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
  },
  68: {
    index: 68,
    name: 'Ant',
    price: 80,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.ROTTEN_FOOD],
    collected: false,
    haveModel: false,
  },
  69: {
    index: 69,
    name: 'Hermit Crab',
    price: 1000,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.BEACH],
    collected: false,
    haveModel: false,
  },
  70: {
    index: 70,
    name: 'Wharf Roach',
    price: 200,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.BEACH],
    collected: false,
    haveModel: false,
    notes: 'Appears on rocks',
  },
  71: {
    index: 71,
    name: 'Fly',
    price: 60,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.TRASH],
    collected: false,
    haveModel: false,
  },
  72: {
    index: 72,
    name: 'Mosquito',
    price: 130,
    type: CritterType.BUG,
    monthsActive: [{ start: 5, end: 8 }],
    timesActive: [{ start: 17, end: 4 }],
    location: [BugLocation.FLYING],
    collected: false,
    haveModel: false,
  },
  73: {
    index: 73,
    name: 'Flea',
    price: 70,
    type: CritterType.BUG,
    monthsActive: [{ start: 3, end: 10 }],
    timesActive: [],
    location: [BugLocation.VILLAGER],
    collected: false,
    haveModel: false,
    notes: 'Appears jumping on villagers',
  },
  74: {
    index: 74,
    name: 'Snail',
    price: 250,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [],
    location: [BugLocation.ROCK, BugLocation.SHRUB],
    collected: false,
    haveModel: false,
    notes: 'Appears during rainy weather',
  },
  75: {
    index: 75,
    name: 'Pill Bug',
    price: 250,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 23, end: 16 }],
    location: [BugLocation.ROCK],
    collected: false,
    haveModel: false,
    notes: 'Appears upon striking rocks with tools',
  },
  76: {
    index: 76,
    name: 'Centipede',
    price: 300,
    type: CritterType.BUG,
    monthsActive: [{ start: 8, end: 5 }],
    timesActive: [{ start: 16, end: 23 }],
    location: [BugLocation.ROCK],
    collected: false,
    haveModel: false,
    notes: 'Appears upon striking rocks with tools',
  },
  77: {
    index: 77,
    name: 'Spider',
    price: 480,
    type: CritterType.BUG,
    monthsActive: [],
    timesActive: [{ start: 19, end: 8 }],
    location: [BugLocation.TREE_SHAKE],
    collected: false,
    haveModel: false,
  },
  78: {
    index: 78,
    name: 'Tarantula',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 10, end: 3 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Will attack if threatened by net, approach when calm',
  },
  79: {
    index: 79,
    name: 'Scorpion',
    price: 8000,
    type: CritterType.BUG,
    monthsActive: [{ start: 4, end: 9 }],
    timesActive: [{ start: 19, end: 4 }],
    location: [BugLocation.GROUND],
    collected: false,
    haveModel: false,
    notes: 'Will attack if threatened by net, approach when calm',
  },
};
